import type { Property, RentPayment, Tenant } from "@/lib/types/domain";

// Static demo dataset. Dates are generated relative to "today" at import
// time so the dashboard always feels current when running without a
// connected Supabase project.

function daysFromNow(days: number) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const DEMO_OWNER_ID = "demo-owner";

export const demoProperties: Property[] = [
  {
    id: "prop-1",
    owner_id: DEMO_OWNER_ID,
    name: "Maple Ridge Apartments",
    address: "128 Maple Ridge Rd",
    city: "Austin",
    state: "TX",
    postal_code: "78701",
    property_type: "apartment",
    units: 8,
    monthly_rent: 1450,
    status: "active",
    notes: "Recently renovated common area and laundry room.",
    created_at: daysFromNow(-410),
    updated_at: daysFromNow(-12),
  },
  {
    id: "prop-2",
    owner_id: DEMO_OWNER_ID,
    name: "Sunset Duplex",
    address: "45 Sunset Ave",
    city: "Austin",
    state: "TX",
    postal_code: "78704",
    property_type: "duplex",
    units: 2,
    monthly_rent: 1900,
    status: "active",
    notes: "",
    created_at: daysFromNow(-280),
    updated_at: daysFromNow(-40),
  },
  {
    id: "prop-3",
    owner_id: DEMO_OWNER_ID,
    name: "Downtown Loft 4B",
    address: "900 Congress Ave, Unit 4B",
    city: "Austin",
    state: "TX",
    postal_code: "78701",
    property_type: "condo",
    units: 1,
    monthly_rent: 2100,
    status: "active",
    notes: "HOA covers water and trash.",
    created_at: daysFromNow(-190),
    updated_at: daysFromNow(-5),
  },
  {
    id: "prop-4",
    owner_id: DEMO_OWNER_ID,
    name: "Riverside House",
    address: "212 Riverside Dr",
    city: "Round Rock",
    state: "TX",
    postal_code: "78664",
    property_type: "house",
    units: 1,
    monthly_rent: 2450,
    status: "active",
    notes: "Tenant handles lawn care per lease.",
    created_at: daysFromNow(-620),
    updated_at: daysFromNow(-90),
  },
  {
    id: "prop-5",
    owner_id: DEMO_OWNER_ID,
    name: "Elm Street Retail Space",
    address: "77 Elm St",
    city: "Austin",
    state: "TX",
    postal_code: "78702",
    property_type: "commercial",
    units: 1,
    monthly_rent: 3200,
    status: "inactive",
    notes: "Between tenants — listed with commercial broker.",
    created_at: daysFromNow(-150),
    updated_at: daysFromNow(-2),
  },
];

export const demoTenants: Tenant[] = [
  {
    id: "ten-1",
    owner_id: DEMO_OWNER_ID,
    property_id: "prop-1",
    full_name: "Jordan Blake",
    email: "jordan.blake@example.com",
    phone: "(512) 555-0143",
    unit: "Unit 2",
    lease_start: daysFromNow(-300),
    lease_end: daysFromNow(65),
    monthly_rent: 1450,
    security_deposit: 1450,
    status: "active",
    notes: "",
    created_at: daysFromNow(-300),
    updated_at: daysFromNow(-30),
  },
  {
    id: "ten-2",
    owner_id: DEMO_OWNER_ID,
    property_id: "prop-1",
    full_name: "Priya Nair",
    email: "priya.nair@example.com",
    phone: "(512) 555-0178",
    unit: "Unit 5",
    lease_start: daysFromNow(-120),
    lease_end: daysFromNow(245),
    monthly_rent: 1500,
    security_deposit: 1500,
    status: "active",
    notes: "Requested renewal — send new lease in 60 days.",
    created_at: daysFromNow(-120),
    updated_at: daysFromNow(-10),
  },
  {
    id: "ten-3",
    owner_id: DEMO_OWNER_ID,
    property_id: "prop-2",
    full_name: "Marcus Webb",
    email: "marcus.webb@example.com",
    phone: "(512) 555-0122",
    unit: "Unit A",
    lease_start: daysFromNow(-500),
    lease_end: daysFromNow(-30),
    monthly_rent: 1900,
    security_deposit: 1900,
    status: "former",
    notes: "Moved out — unit being turned over.",
    created_at: daysFromNow(-500),
    updated_at: daysFromNow(-30),
  },
  {
    id: "ten-4",
    owner_id: DEMO_OWNER_ID,
    property_id: "prop-3",
    full_name: "Elena Ruiz",
    email: "elena.ruiz@example.com",
    phone: "(512) 555-0199",
    unit: null,
    lease_start: daysFromNow(-90),
    lease_end: daysFromNow(275),
    monthly_rent: 2100,
    security_deposit: 2100,
    status: "active",
    notes: "",
    created_at: daysFromNow(-90),
    updated_at: daysFromNow(-4),
  },
  {
    id: "ten-5",
    owner_id: DEMO_OWNER_ID,
    property_id: "prop-4",
    full_name: "Sam Okafor",
    email: "sam.okafor@example.com",
    phone: "(512) 555-0110",
    unit: null,
    lease_start: daysFromNow(-60),
    lease_end: daysFromNow(305),
    monthly_rent: 2450,
    security_deposit: 2450,
    status: "active",
    notes: "",
    created_at: daysFromNow(-60),
    updated_at: daysFromNow(-1),
  },
  {
    id: "ten-6",
    owner_id: DEMO_OWNER_ID,
    property_id: "prop-2",
    full_name: "Taylor Nguyen",
    email: "taylor.nguyen@example.com",
    phone: "(512) 555-0166",
    unit: "Unit B",
    lease_start: daysFromNow(15),
    lease_end: daysFromNow(380),
    monthly_rent: 1950,
    security_deposit: 1950,
    status: "pending",
    notes: "Lease signed, move-in scheduled.",
    created_at: daysFromNow(-5),
    updated_at: daysFromNow(-1),
  },
];

export const demoRentPayments: RentPayment[] = [
  {
    id: "pay-1",
    owner_id: DEMO_OWNER_ID,
    tenant_id: "ten-1",
    property_id: "prop-1",
    amount: 1450,
    due_date: daysFromNow(-3),
    payment_date: daysFromNow(-4),
    status: "paid",
    payment_method: "bank_transfer",
    notes: "",
    created_at: daysFromNow(-4),
    updated_at: daysFromNow(-4),
  },
  {
    id: "pay-2",
    owner_id: DEMO_OWNER_ID,
    tenant_id: "ten-2",
    property_id: "prop-1",
    amount: 1500,
    due_date: daysFromNow(-3),
    payment_date: daysFromNow(-2),
    status: "paid",
    payment_method: "card",
    notes: "",
    created_at: daysFromNow(-2),
    updated_at: daysFromNow(-2),
  },
  {
    id: "pay-3",
    owner_id: DEMO_OWNER_ID,
    tenant_id: "ten-4",
    property_id: "prop-3",
    amount: 2100,
    due_date: daysFromNow(-8),
    payment_date: null,
    status: "late",
    payment_method: null,
    notes: "Follow up sent on the 3rd.",
    created_at: daysFromNow(-8),
    updated_at: daysFromNow(-1),
  },
  {
    id: "pay-4",
    owner_id: DEMO_OWNER_ID,
    tenant_id: "ten-5",
    property_id: "prop-4",
    amount: 2450,
    due_date: daysFromNow(-3),
    payment_date: daysFromNow(-3),
    status: "paid",
    payment_method: "check",
    notes: "",
    created_at: daysFromNow(-3),
    updated_at: daysFromNow(-3),
  },
  {
    id: "pay-5",
    owner_id: DEMO_OWNER_ID,
    tenant_id: "ten-1",
    property_id: "prop-1",
    amount: 1450,
    due_date: daysFromNow(27),
    payment_date: null,
    status: "pending",
    payment_method: null,
    notes: "",
    created_at: daysFromNow(-3),
    updated_at: daysFromNow(-3),
  },
  {
    id: "pay-6",
    owner_id: DEMO_OWNER_ID,
    tenant_id: "ten-2",
    property_id: "prop-1",
    amount: 1500,
    due_date: daysFromNow(27),
    payment_date: null,
    status: "pending",
    payment_method: null,
    notes: "",
    created_at: daysFromNow(-2),
    updated_at: daysFromNow(-2),
  },
  {
    id: "pay-7",
    owner_id: DEMO_OWNER_ID,
    tenant_id: "ten-4",
    property_id: "prop-3",
    amount: 2100,
    due_date: daysFromNow(22),
    payment_date: null,
    status: "pending",
    payment_method: null,
    notes: "",
    created_at: daysFromNow(-1),
    updated_at: daysFromNow(-1),
  },
  {
    id: "pay-8",
    owner_id: DEMO_OWNER_ID,
    tenant_id: "ten-5",
    property_id: "prop-4",
    amount: 1200,
    due_date: daysFromNow(-33),
    payment_date: daysFromNow(-33),
    status: "partial",
    payment_method: "cash",
    notes: "Remaining $1,250 paid two weeks later.",
    created_at: daysFromNow(-33),
    updated_at: daysFromNow(-33),
  },
];
